- type: job
  id: Paramedic
  name: job-name-paramedic
  description: job-description-paramedic
  playTimeTracker: JobParamedic
  requirements:
    - !type:RoleTimeRequirement
      role: JobMedicalDoctor
      time: 14400 #4 hrs
    - !type:OverallPlaytimeRequirement
      time: 54000 # 15 hrs
  startingGear: ParamedicGear
  icon: "Paramedic"
  supervisors: job-supervisors-cmo
  canBeAntag: false
  access:
  - Medical
  - Maintenance
  - External
  extendedAccess:
  - Chemistry

- type: startingGear
  id: ParamedicGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitParamedic
    back: ADTClothingBackpackParamedicalMedicalFilled
    shoes: ClothingShoesColorWhite
    id: ParamedicPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltParamedicFilled
    underwearb: ClothingUnderwearBottomBoxersWhite # Sirena-Underwear
  underweart: ClothingUnderwearTopBraWhite # Sirena-Underwear
  underwearb: ClothingUnderwearBottomPantiesWhite # Sirena-Underwear
  innerclothingskirt: ClothingUniformJumpskirtParamedic
  satchel: ADTClothingBackpackSatchelParamedicalFilled
  duffelbag: ADTClothingBackpackDuffelParamedicalFilled
