stages:
  - install  
  - build
  - test

install-dep:
  stage: install
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_SUBMODULE_UPDATE_FLAGS: --init --depth 50 --recursive --jobs 4
  before_script:
    - \[ -d ../artifacts \] || mkdir ../artifacts
  script:
    - echo "Install dependenses ..."

build-project:       
  stage: build
  variables:
    GITHUB_ACTIONS: 1
    GIT_CLEAN_FLAGS: none
    GIT_CHECKOUT: none
  dependencies: []
  script:
    - |
      echo "Restore Projects ..."
      dotnet restore
      echo "Build Projects ..."
      dotnet build --configuration Release --no-restore /p:WarningsAsErrors= /m
      dotnet run --project Content.YAMLLinter/Content.YAMLLinter.csproj --no-build
      echo "Compile complete."

yaml-test:       
  stage: test
  variables:
    GITHUB_ACTIONS: 1
    GIT_CLEAN_FLAGS: none
    GIT_CHECKOUT: none
  dependencies: []
  script:
    - dotnet run --project Content.YAMLLinter/Content.YAMLLinter.csproj --no-build      

content-test:       
  stage: test
  needs: ["yaml-test"]
  variables:
    GITHUB_ACTIONS: 1
    GIT_CLEAN_FLAGS: none
    GIT_CHECKOUT: none
  dependencies: []
  before_script:
    - \[ -d ../artifacts \] || mkdir ../artifacts
  script:
    - dotnet test --configuration Tools --no-build Content.Tests/Content.Tests.csproj --logger "junit;LogFilePath=../artifacts/content-tests.xml"
  artifacts:
    paths: 
      - ./artifacts/content-tests.xml
    reports:
      junit: ./artifacts/content-tests.xml

unit-test:       
  stage: test
  needs: ["yaml-test"]
  variables:
    DOTNET_gcServer: 1
    GITHUB_ACTIONS: 1
    GIT_CLEAN_FLAGS: none
    GIT_CHECKOUT: none
  dependencies: []
  before_script:
    - \[ -d ../artifacts \] || mkdir ../artifacts
  script:
    - dotnet test --configuration Tools --no-build Content.IntegrationTests/Content.IntegrationTests.csproj --logger "junit;LogFilePath=../artifacts/unit-tests.xml"
  artifacts:
    paths: 
      - ./artifacts/unit-tests.xml
    reports:
      junit: ./artifacts/unit-tests.xml


remove-build:
  stage: .post
  when: on_failure
  script:
    - cd ..
    - rm -R space_station
