- type: gameMapPool
  id: DefaultMapPool
  maps:
  - CorvaxDelta
  - Aspid
  - Barratry
  - Cluster
  - Core
  - Fland
  - Kettle
  - Marathon
  - Meta
  - Moose
  - Omega
  - Origin
  - Saltern
  - Packed
  - Bagel
  - Box
  - Quadro
