- type: job
  id: BlueShieldOfficer
  name: job-name-blueshieldofficer
  playTimeTracker: JobBlueShieldOfficer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Command
      time: 72000
  startingGear: BlueShieldOfficerGear
  icon: "blueshield"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
    - Command
    - Brig
    - Security
    - Armory
    - Maintenance
    - Service
    - External
    - Research
    - Medical
    - Engineering
    - Cargo

- type: playTimeTracker
  id: JobBlueShieldOfficer

- type: startingGear
  id: BlueShieldOfficerGear
  equipment:
    head: ClothingHeadHatBeretWarden
    eyes: ClothingEyesGlassesSecurity
    ears: ClothingHeadsetAltCommand
    jumpsuit: ClothingUniformJumpsuitNanotrasen
    back: ClothingBackpackBlueShieldOfficerFilled
    shoes: ClothingShoesBootsCombatFilled
    outerClothing: ClothingOuterVestWeb
    belt: ClothingBeltMilitaryWebbingMedFilled
    gloves: ClothingHandsGlovesCombat
    id: BlueShieldOfficerPDA

- type: entity
  id: SpawnBlueShieldOfficer
  parent: SpawnPointJobBase
  name: BlueShieldOfficer
  components:
    - type: SpawnPoint
      job_id: BlueShieldOfficer
    - type: Sprite
      layers:
        - state: green
        - state: hop

- type: entity
  parent: BasePDA
  id: BlueShieldOfficerPDA
  name: BlueShield PDA
  description: Это пахнет защитой.
  components:
    - type: PDA
      id: BlueShieldOfficerIDCard
      state: pda-ert
    - type: PDABorderColor
      borderColor: "#A32D26"
      accentVColor: "#447987"
    - type: Icon
      state: pda-ert
    - type: HealthAnalyzer
      scanDelay: 1.2

- type: entity
  parent: IDCardStandard
  id: BlueShieldOfficerIDCard
  name: Blue Shield Officer ID card
  components:
    - type: Sprite
      layers:
        - state: default
        - state: ert_security
    - type: PresetIdCard
      job: BlueShieldOfficer
