- type: entity
  parent: ClothingHeadset
  id: ClothingHeadsetMagistrat
  name: magistrat headset
  description: magistrat's headset.
  components:
  - type: ContainerFill
    containers:
      key_slots:
      - ADTEncryptionKeyLawyer
      - EncryptionKeyCommand
      - EncryptionKeySecurity
      - EncryptionKeyCommon
      - EncryptionKeyCentCom
  - type: Sprite
    sprite: Clothing/Ears/Headsets/servicesecurity.rsi
