- type: entity
  id: ADTTallRobotMekaBase
  parent: BaseBorgChassisNT
  suffix: TallRobot
  abstract: true
  components:
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeCircle
          radius: 0.45
        density: 150
        mask:
        - MobMask
        layer:
        - MobLayer
  - type: BorgChassis
    maxModules: 6
  - type: MovementSpeedModifier
    baseWalkSpeed : 2.5
    baseSprintSpeed : 4.5
  - type: MobThresholds
    thresholds:
      0: Alive
      120: Critical
      220: Dead

- type: entity
  id: ADTTallRobotFMekaBase
  parent: ADTTallRobotMekaBase
  suffix: TallRobot
  abstract: true
  components:
  - type: Sprite
    scale: 0.85, 0.85
