name: Check Merge Conflicts

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  Label:
    if: github.actor != 'IanComradeBot'
    runs-on: ubuntu-latest
    steps:
      - name: Check for Merge Conflicts
        uses: eps1lon/actions-label-merge-conflict@releases/2.x
        with:
          dirtyLabel: "Merge Conflict"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          commentOnDirty: "This pull request has conflicts, please resolve those before we can evaluate the pull request."
