name: Publish

concurrency:
  group: publish

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'
  workflow_run:
    workflows: [Build & Test Release]
    types: [completed]

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: sudo apt-get install -y python3-paramiko python3-lxml
  
    - name: Update manifest JSON
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.BUILDS_HOST }}
        port: ${{ secrets.BUILDS_PORT }}
        username: ${{ secrets.BUILDS_USERNAME }}
        key: ${{ secrets.BUILDS_SSH_KEY }}
        script: python3 ~/manifest.py --version ${{ github.sha }}
