name: Update ERP

on:
  push:
    branches:
      - master

permissions:
  # Need `contents: read` to checkout the repository
  # Need `contents: write` to merge branches
  contents: write

jobs:
  update-production:
    name: Merge master into production after a PR is merged
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Let's get all the branches
      - name: Merge Master to ERP branch
        uses: devvspaces/merge-branches@v1
        with:
          token: ${{ github.token }}
          from_branch: master
          to_branch: ERP
  ci-success:
    name: Update ERP
    needs:
      - update-production
    runs-on: ubuntu-latest
    steps:
      - name: CI succeeded
        run: exit 0
